# Generated by Django 3.2 on 2022-03-02 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(db_index=True, unique=True, verbose_name='исходный URL')),
                ('url_hash', models.CharField(max_length=100, unique=True, verbose_name='идентификатор')),
                ('short_url', models.URLField(blank=True, null=True, verbose_name='сокращенный URl')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время создания')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
    ]
